### ISSUE TITLE
JSON かどうか判定する関数について

### ISSUE THREAD

**Issue by studio3104** [ryoishim/LINExAWSServerless#21]
たぶんこれどこからも呼ばれてないですよね？
呼ばれていない実装は削除してしまいましょう。

https://github.com/ryoishim/LINExAWSServerless/blob/969410163431fd8f69f3c45c2ec001e490b214d9/function.py#L22-L38

**Comment by studio3104** [comment]
もし今後使うということであったら内容を見直してほしいです。
`ValueError` を catch するだけで十分です。

```python
Python 3.6.8 (default, Jan 16 2019, 19:30:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import json

In [2]: issubclass(json.JSONDecodeError, ValueError)
Out[2]: True

In [3]:
```

**Comment by studio3104** [comment]
例外基底クラスで catch するのは特別に理由がない限りはしないほうがいいです。

https://github.com/ryoishim/LINExAWSServerless/blob/969410163431fd8f69f3c45c2ec001e490b214d9/function.py#L34-L37

ここにひっかかる場合は JSON じゃなかった場合以外の理由になるはずなので、であればそのまま素直に例外が上がってしまうほうがいいです。

**Comment by studio3104** [comment]
これ両方出す必要はないのかなーという気がします

https://github.com/ryoishim/LINExAWSServerless/blob/969410163431fd8f69f3c45c2ec001e490b214d9/function.py#L31-L32

```python
Python 3.6.8 (default, Jan 16 2019, 19:30:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys

In [2]: def hoge():
   ...:     raise
   ...:

In [3]: try:
   ...:     hoge()
   ...: except RuntimeError as e:
   ...:     print(e)
   ...:     print(sys.exc_info())
   ...:
No active exception to reraise
(<class 'RuntimeError'>, RuntimeError('No active exception to reraise',), <traceback object at 0x10f878d88>)

In [4]:
```

**Comment by studio3104** [comment]
判定したあとに実際の実装でもう一回 `json.dumps` するとするのであれば非常に非効率かなという気が

https://github.com/ryoishim/LINExAWSServerless/blob/969410163431fd8f69f3c45c2ec001e490b214d9/function.py#L22-L24

**Comment by ryoishim** [comment]
ごめんなさいこれはSQSから取得したbodyの型をイジイジしてた時にチェッカとして使ってたもので、そのうち削除します。

**Comment by ryoishim** [comment]
削除しました。
